version: '3.9'

services:
  database:
    container_name: mysql
    image: mysql
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_ROOT_PASSWORD: Max111111
    ports:
      - "3306:3306"

  database-test:
    container_name: mysql-test
    image: mysql
    environment:
      MYSQL_DATABASE: book_store
      MYSQL_ROOT_PASSWORD: Max111111
    ports:
      - "3308:3306"

  hoverfly:
    container_name: hoverfly
    image: spectolabs/hoverfly:v1.5.3
    command:
      - "-webserver"
      - "-response-body-files-path=/hoverfly_app/responses"
      - "-import=/hoverfly_app/simulations/recommend.simulation.json"
    volumes:
      - "$PWD/hoverfly:/hoverfly_app:ro"
    ports:
      - "8500:8500"
