api_login_check:
    path: /api/v1/auth/login

api_refresh_token:
    path: /api/v1/auth/refresh

controllers:
    resource:
        path: ../src/Controller/Api
        namespace: App\Controller\Api
    type: attribute
    requirements:

vue_routes:
    path: /{wildcard}
    controller: App\Controller\BaseController::index
    requirements:
        wildcard: .*
